const configRoutes = {
  home: "/",
  register: "/register",
  login: "/login",
  googleLogin: "/signin-google",
  facebookLogin: "/signin-facebook",
  user: "/user",
  favorite: "/favorite",
  contact: "/contact",
  about: "/about",
  resetPassword: "/reset-password",
  productDetail: "/product-detail/:productId",
  category: "/category/:title",
  manager: "/manager",
  profile: "/manager/profile",
  link: "/manager/links",
  order: "/manager/orders",
  return: "/manager/returns",
  cancel: "/manager/cancels",
  review: "/manager/reviews",
  confirm: "/confirm-email",
  cart: "/cart",
  address: "/manager/address",
  checkout: "/cart/checkout",
  payment: "/payment",
  paymentError: "/payment/error",
  error: "*",
}

export default configRoutes;